### ISSUE TITLE
Decide what features to be incorporated

### ISSUE THREAD

**Issue by stevenJoyce** [EvanGreaney/TACKZO#3]

**Comment by EvanGreaney** [comment]
Ive found an API we can use for recipes as you can search using calories , carbs ...etc. https://spoonacular.com/food-api

**Comment by stevenJoyce** [comment]
The api looks great, really detailed and easy to follow. I created the gitpod files and they are in a branch. I will double check they work before merging the files. Maybe merge the files in the meeting.


________________________________
